services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 127.0.0.1:5672:5672
        - 127.0.0.1:15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - rabbitmq_net

  smtpd:
    build: .
    container_name: 'email_server'
    ports:
        - 127.0.0.1:1025:1025

networks:
  rabbitmq_net:
    driver: bridge
